import { ThemeProvider } from "@/components/provider/theme-provider";
import { LayoutProvider } from "@/layout/context/layoutcontext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // <Provider store={store}>
        <html lang="ko" suppressHydrationWarning>
            {/* <Header /> */}
            <StoreProvider>
                <body className={inter.className}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <LayoutProvider>{children}</LayoutProvider>
                    </ThemeProvider>
                </body>
            </StoreProvider>
        </html>
        // </Provider>
    );
}
